name: CI (Linux)

on: [push, pull_request]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start ArangoDB by docker-compose
        run: |
          docker-compose up -d
          sleep 30
          docker-compose logs

      - name: Set up ArangoDB for test
        run: bash tests/init_db.sh

      - name: rustfmt
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: fmt
          args: --all -- --check

      - name: check build (blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: check
          args:  --features "rocksdb cluster enterprise blocking" --lib

      - name: test (blocking)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --features "rocksdb cluster enterprise blocking" --lib

      - name: check build (default features)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: check
          args: --all --bins --examples --tests

      - name: tests (default features)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        timeout-minutes: 40
        with:
          command: test
          args: --all --no-fail-fast -- --nocapture

      - name: check build (async rustls)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: check
          args: --no-default-features --features "rustls rocksdb cluster enterprise" --lib

      - name: test (async rustls)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rustls rocksdb cluster enterprise" --lib

      - name: check build (blocking rustls)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: check
          args: --no-default-features --features "rustls rocksdb cluster enterprise blocking" --lib

      - name: test (blocking rustls)
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        timeout-minutes: 40
        with:
          command: test
          args: --no-fail-fast --no-default-features --features "rustls rocksdb cluster enterprise blocking" --lib

  mmfiles:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Start ArangoDB by docker
        run: |
          docker run -e ARANGO_STORAGE_ENGINE=mmfiles -e ARANGO_ROOT_PASSWORD=KWNngteTps7XjrNv -p 8529:8529 -d --name arangodb arangodb/arangodb
          sleep 30
          docker logs arangodb

      - name: Set up ArangoDB for test
        run: bash tests/init_db.sh

      - name: check build
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        with:
          command: check
          args: --all --bins --examples --tests --features "mmfiles cluster enterprise blocking" --lib

      - name: tests
        uses: actions-rs/cargo@v1
        env:
          RUST_LOG: arangors_lite=trace
        timeout-minutes: 40
        with:
          command: test
          args: --all --no-fail-fast --features "mmfiles cluster enterprise blocking"

  doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: doc
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --all --no-deps